# Generated by Django 6.0.7 on 2026-08-19 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0002_initial'),
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='threads.reply'),
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='cores.status'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='threads.reply'),
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='threads.category'),
        ),
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='cores.status'),
        ),
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='threads.thread'),
        ),
        migrations.AddField(
            model_name='image',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='threads.thread'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title', '-created_at'], name='idx_category_title_create'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['status', '-created_at'], name='idx_thread_status_created'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', '-updated_at'], name='idx_thread_cat_created'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', '-updated_at'], name='idx_thread_cat_updated'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(condition=models.Q(('view_count__gte', 100)), fields=['category', '-view_count'], name='idx_thread_cat_views'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(condition=models.Q(('like_count__gte', 100)), fields=['category', '-like_count'], name='idx_thread_cat_likes'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', '-created_at'], name='idx_thread_user_created_at'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['user', 'thread', '-created_at'], name='idx_user_thread_create'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['thread', 'display_order'], name='idx_image_thread_order'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['reply', 'display_order'], name='idx_image_reply_order'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('is_thumbnail', True)), fields=('thread',), name='unique_thumbnail_per_thread'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(condition=models.Q(('thread__isnull', False), ('reply__isnull', False), _negated=True), name='image_not_both_thread_and_reply'),
        ),
    ]
