# Generated by Django 6.0.7 on 2026-08-13 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(condition=models.Q(('thread__isnull', False), ('reply__isnull', False), _negated=True), name='image_not_both_thread_and_reply'),
        ),
    ]
