# Generated by Django 6.0.7 on 2026-08-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0003_initial'),
        ('threads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like', to='threads.reply')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like', to='threads.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'reply', '-created_at'], name='idx_like_user_reply_create'), models.Index(fields=['user', 'thread', '-created_at'], name='idx_like_user_thread_create')],
                'constraints': [models.UniqueConstraint(fields=('user', 'thread'), name='unique_user_thread_like'), models.UniqueConstraint(fields=('user', 'reply'), name='unique_user_reply_like')],
            },
        ),
    ]
