# Generated by Django 6.0.7 on 2026-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0005_remove_like_unique_user_thread_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
