# Generated by Django 6.0.7 on 2026-08-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0006_alter_bookmark_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
