# Generated by Django 6.0.7 on 2026-08-19 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('status_type', 'status_name'), name='unique_status_type_name'),
        ),
        migrations.AddIndex(
            model_name='activity_log',
            index=models.Index(fields=['user', '-created_at'], name='idx_logs_user_create'),
        ),
        migrations.AddIndex(
            model_name='activity_log',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='idx_logs_target_create'),
        ),
    ]
