# Generated by Django 6.0.7 on 2026-08-31 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='action',
            field=models.CharField(choices=[('create_thread', 'Created Thread'), ('update_thread', 'Updated Thread'), ('delete_thread', 'Deleted Thread'), ('archive_thread', 'Archived Thread'), ('like_thread', 'Liked Thread'), ('unlike_thread', 'Unliked Thread'), ('bookmark_thread', 'Bookmarked Thread'), ('unbookmark_thread', 'Unbookmarked Thread'), ('create_reply', 'Created Reply'), ('update_reply', 'Updated Reply'), ('delete_reply', 'Deleted Reply')]),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
